# Generated by Django 4.0.4 on 2022-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField()),
                ('delivery_free', models.BooleanField()),
                ('date_of_launch', models.DateField()),
                ('category_type', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
